AWSTemplateFormatVersion: "2010-09-09"
Description: Backend stack for Photo Lab App

Parameters:
  AppName:
    Type: String
    Default: photo-lab
  GitHubRepoOwner:
    Type: String
  GitHubRepoName:
    Type: String

Resources:
  # --- ECR Repository ---
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${AppName}-backend"

  # --- ECS Cluster ---
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AppName}-backend-cluster"

  # --- SSM Parameters ---
  ECRRepositoryUriParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/backend/ECRRepositoryUri"
      Type: String
      Value: !GetAtt ECRRepository.RepositoryUri
      Overwrite: true

  ECSClusterNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/backend/ECSClusterName"
      Type: String
      Value: !Ref ECSCluster
      Overwrite: true

  ECSServiceNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/backend/ECSServiceName"
      Type: String
      Value: !Sub "${AppName}-backend-service"
      Overwrite: true

Outputs:
  ECRRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub "${AppName}-BackendECRUri"

  ECSClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${AppName}-BackendECSClusterName"
