AWSTemplateFormatVersion: "2010-09-09"
Description: Frontend stack for Photo Lab App

Parameters:
  AppName:
    Type: String
    Default: photo-lab

Resources:
  # --- S3 Bucket for frontend ---
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-frontend-${AWS::AccountId}-${AWS::Region}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # --- CloudFront Distribution ---
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access Identity for frontend bucket

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt FrontendBucket.RegionalDomainName
            Id: FrontendOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          TargetOriginId: FrontendOrigin
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # --- SSM Parameters ---
  FrontendBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/frontend/S3BucketName"
      Type: String
      Value: !Ref FrontendBucket
      Overwrite: true

  FrontendCFParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/frontend/CloudFrontDistributionId"
      Type: String
      Value: !Ref FrontendDistribution
      Overwrite: true

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${AppName}-FrontendBucket"

  FrontendDistributionId:
    Value: !Ref FrontendDistribution
    Export:
      Name: !Sub "${AppName}-FrontendCFId"

  FrontendURL:
    Value: !GetAtt FrontendDistribution.DomainName
    Export:
      Name: !Sub "${AppName}-FrontendURL"
