AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend stack for Photo Lab application

Parameters:
  EnvironmentName:
    Type: String
    Default: frontend
  DeploymentZipFileName:
    Type: String
    Default: deployment-files.zip
  AllowedGithubRepo:
    Type: String
    Default: XzibiT-Collins/photo-lab-frontend
  AllowedGithubBranch:
    Type: String
    Default: refs/heads/main

Resources:

  ####################################
  # S3 Bucket for frontend
  ####################################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-bucket-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-bucket"

  ####################################
  # CloudFront Distribution Parameter
  ####################################
  FrontendCloudFrontDistributionId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${EnvironmentName}/CloudFrontDistributionId"
      Type: String
      Value: "TODO-ADD-CF-DISTRIBUTION-ID"

Outputs:
  FrontendBucketName:
    Description: S3 Bucket name for frontend
    Value: !Ref FrontendBucket

  CloudFrontDistributionParameter:
    Description: SSM Parameter name for CloudFront Distribution ID
    Value: !Ref FrontendCloudFrontDistributionId
