AWSTemplateFormatVersion: "2010-09-09"
Description: Frontend stack for Photo Lab App with GitHub OIDC and SSM

Parameters:
  AppName:
    Type: String
    Default: photo-lab
  GitHubRepoOwner:
    Type: String
    Description: GitHub organization or username (e.g., "your-org")
  GitHubRepoName:
    Type: String
    Description: GitHub repository name (e.g., "photo-frontend")

Resources:
  # ---------------- S3 Bucket ----------------
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-frontend-${AWS::AccountId}-${AWS::Region}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # ---------------- CloudFront ----------------
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access Identity for frontend bucket

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt FrontendBucket.RegionalDomainName
            Id: FrontendOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          TargetOriginId: FrontendOrigin
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # ---------------- GitHub OIDC ----------------
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: ["sts.amazonaws.com"]
      ThumbprintList: ["6938fd4d98bab03faadb97b34396831e3780aea1"]

  GitHubOIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-GitHubOIDCRole-Frontend"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubRepoOwner}/${GitHubRepoName}:ref:refs/heads/main"
      Policies:
        - PolicyName: FrontendS3Deploy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub "${FrontendBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "${FrontendBucket.Arn}"
        - PolicyName: FrontendCloudFrontInvalidate
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: "*"

  # -----------------------------
  # SSM Parameters
  # -----------------------------
  FrontendBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/frontend/S3BucketName"
      Type: String
      Value: !Ref FrontendBucket

  FrontendCloudFrontParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/frontend/CloudFrontDistributionId"
      Type: String
      Value: !Ref FrontendDistribution

  GitHubOIDCRoleFrontendParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/frontend/GitHubOIDCRoleArn"
      Type: String
      Value: !GetAtt GitHubOIDCRole.Arn

Outputs:
  FrontendURL:
    Description: CloudFront distribution URL
    Value: !GetAtt FrontendDistribution.DomainName
    Export:
      Name: !Sub "${AppName}-FrontendURL"

  FrontendBucketName:
    Description: S3 bucket name
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${AppName}-FrontendBucketName"

  GitHubOIDCRoleArn:
    Description: OIDC Role ARN for GitHub Actions
    Value: !GetAtt GitHubOIDCRole.Arn
    Export:
      Name: !Sub "${AppName}-GitHubOIDCRoleArn-Frontend"
