AWSTemplateFormatVersion: "2010-09-09"
Description: Networking resources for Photo Lab App

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: photo-lab-vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Postgres access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # tighten later

Outputs:
  VPCId:
    Value: !Ref VPC
    Export:
      Name: PhotoLab-VPCId

  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Export:
      Name: PhotoLab-PublicSubnet1

  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Export:
      Name: PhotoLab-PublicSubnet2

  DBSecurityGroupId:
    Value: !Ref DBSecurityGroup
    Export:
      Name: PhotoLab-DBSecurityGroup
