AWSTemplateFormatVersion: "2010-09-09"
Description: Networking resources for Photo Lab App (with shared GitHub OIDC provider)

Resources:
  ####################################
  # VPC and Subnets
  ####################################
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: photo-lab-vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true

  ####################################
  # Security Group
  ####################################
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Postgres access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # tighten later

  ####################################
  # GitHub OIDC Provider (Shared)
  ####################################
  GitHubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 7560d6f40fa55195f740ee2b1b7c0b4836cbe103

  ####################################
  # GitHub Actions Role (Shared for frontend & backend)
  ####################################
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: photo-lab-github-actions
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: "repo:*:ref:refs/heads/main"
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      Path: "/"
      Policies:
        - PolicyName: S3FrontendBackendAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::frontend-bucket-*"   # frontend S3
                  - !Sub "arn:aws:s3:::frontend-bucket-*/*"
                  - !Sub "arn:aws:s3:::backend-bucket-*"    # backend S3
                  - !Sub "arn:aws:s3:::backend-bucket-*/*"
        - PolicyName: ECRPushAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                Resource: "*"  # or specific backend ECR ARN
        - PolicyName: RDSSecretsAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                Resource: "*"  # restrict to actual secrets later

Outputs:
  VPCId:
    Value: !Ref VPC
    Export:
      Name: PhotoLab-VPCId

  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Export:
      Name: PhotoLab-PublicSubnet1

  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Export:
      Name: PhotoLab-PublicSubnet2

  DBSecurityGroupId:
    Value: !Ref DBSecurityGroup
    Export:
      Name: PhotoLab-DBSecurityGroup

  GitHubOIDCProviderArn:
    Description: ARN of the shared GitHub OIDC Provider
    Value: !GetAtt GitHubOidcProvider.Arn
    Export:
      Name: PhotoLab-GitHubOIDCProviderArn

  GitHubActionsRoleArn:
    Description: ARN of the shared GitHub Actions Role
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: PhotoLab-GitHubActionsRoleArn
